import { Locality } from './locality.model';

export class Businesspro {
  constructor(
    public businessName: string,
    public businessType: string,
    public category: string,
    public subCategory: string,
    public contactPerson: string,
    public address: string,
    public numberOfOutlets: string,
    public contactPersonDesignation: string,
    public city: string,
    public contactEmailId: string,
    public locality: string,
    public businessTypeCode: string,
    public pincode: string,
    public gstno: string,
    public contactSeller: boolean,
    public noReturnExchange: boolean,
    public productExchange: boolean,
    public productExchangeDay: string,
    public productReturnOrExchange: boolean,
    public productReturnOrExchangeDay: string,
    public returnAvailable: boolean,
    public returnsAvailableDay: string,
    public noExchangeFlage: boolean,
    public noReturnFlage: boolean,
    public publicPhoneNumber: string,
    public publicEmail: string,
    public storeUrl: string,
    public storeImgUrl: string,
    public shipTimeType: string,
    public shipTimeInterval: string,
    public allOverIndia: boolean,
    public selectLocalities: boolean,
    public area: Array<Locality>|null,
    public freeShip: boolean,
    public chargePerOrder: boolean,
    public orderShipCharge: string,
    public chargePerProd: boolean) {}
  }
 
