export class PG {
  constructor(
    public mode: number,
    public amount: number,
    public sourceId: number,
    public ismobileview: number,
    public email: string,
    public phone: string,
    public mobileNo: string,
    public title: string,
    public txnId: string,
    public surl: string,
    public furl: string,
    public lastName: string,
    public paylinkid: string,
    public firstName: string,
    public merchantId: string,
    public merchantCode: string,
    public udf2: string,
    public udf3: string,
    public udf4: string,
    public udf5: string,
    public mtype: number,
    public hasFundraiser: boolean,
    public fundraiserId: string) { }
}